version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:5432
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./:/user/src/app
      - ./postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/src:/home/daydule/src
      - db_data_volume:/var/lib/postgresql/data

  node_express:
    build: ./
    container_name: node_express
    ports:
      - ${BACKEND_PORT}:3000
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
    depends_on:
      - postgres
    command: ["./wait-for-db-container.sh", "npm", "start"]

volumes:
  db_data_volume:
